services:
  db:
    image: mysql:5.5.60
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: pswd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
